<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE employees[
<!ELEMENT employees (employee+)>
<!ELEMENT employee (id, name, department, designation, email, salary)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
]>
<employees>
<employee>
<id>101</id>
<name>Data Singh</name>
<department>IT</department>
<designation>Software Engineer</designation>
<email>data.singh@example.com</email>
<salary>50000</salary>
</employee>
<employee>
<id>102</id>
<name>gitpull sharma</name>
<department>HR</department>
<designation>HR Manager</designation>
<email>gitpull.sharma@example.com</email>
<salary>60000</salary>
</employee>
</employees>

